# Generated by Django 3.1.7 on 2021-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
