# Generated by Django 3.1.7 on 2021-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210511_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
    ]
