# Generated by Django 3.1.7 on 2021-05-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.CharField(default='', max_length=500)),
                ('processor', models.CharField(default='', max_length=30)),
                ('ram', models.CharField(default='', max_length=30)),
                ('storage', models.IntegerField(default='')),
                ('screen_size', models.IntegerField(default='')),
                ('color', models.CharField(default='', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
