# Generated by Django 3.1.7 on 2021-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
