# Generated by Django 3.1.7 on 2021-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210515_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='ram',
            field=models.IntegerField(choices=[('4', '4'), ('8', '8'), ('12', '12'), ('16', '16')]),
        ),
    ]
