# Generated by Django 3.1.7 on 2021-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210515_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='ram',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('12', '12'), ('16', '16')], max_length=20),
        ),
    ]
