# Generated by Django 3.1.7 on 2021-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='offer_price',
            field=models.IntegerField(null=True),
        ),
    ]
