# Generated by Django 3.1.7 on 2021-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_table_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
