# Generated by Django 3.1.7 on 2021-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210522_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='offer_percentage',
            field=models.FloatField(null=True),
        ),
    ]
