# Generated by Django 3.1.7 on 2021-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_table_offer_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalCoupen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_title', models.CharField(max_length=30)),
                ('coupen_code', models.CharField(max_length=30)),
                ('coupen_offer', models.FloatField()),
                ('validity', models.BooleanField(default=True)),
            ],
        ),
    ]
